### ISSUE TITLE
multiple decks error

### ISSUE THREAD

**Issue by db-keli** [db-keli/kelvin#2]
multiple decks with same domain names will be a problem. decks with same domain names but different passwords should work

**Comment by Kelvinyu1** [comment]
If I can suggest a modification to this issue, rather than letting users have different domains with the same names, if a user were to create a different domain with same name then we can check if the name already exists, and if it does then we can append a "_<nth copy>." An example would be [email, email_1, email_2, ...]. I would still like to work on the original issue but this was just something I thought of.

**Comment by db-keli** [comment]
Great!
I thought of this too after a while
Issues will be updated and discussed clearly on the discord server

**Comment by Nathy-bajo** [comment]
Hello @db-keli. 😄
This is the PR for this. https://github.com/db-keli/kelvin/pull/15
Please let me know if I'm missing anything.

**Comment by db-keli** [comment]
Honestly this is so clear 😌
